numeral = input("입력 진수 결정(16/10/8/2) : ")
number = input("값 입력 : ")
number = int(number, numeral)
print("16진수 ==> ", hex(number))
print("10진수 ==> ", number)
print("8진수 ==> ", oct(number))
print("2진수 ==> ", bin(number))